source 'http://rubygems.org'

gem 'hpricot'     ,'~> 0.8.2'
gem 'json'        ,'~> 1.4.6'
gem 'gitrb'       ,'~> 0.2.7'
gem 'bzip2-ruby'  ,'~> 0.2.6'
gem 'mime-types'  ,'~> 1.16'
gem 'mimemagic'   ,'~> 0.1.7'
gem 'octopussy'   ,'~> 0.3.0'
gem 'hashie'      ,'~> 0.2.2'
gem 'htmlentities','~> 4.2.1'
gem 'feedzirra'   ,'~> 0.0.24'
gem 'erubis'      ,'~> 2.6.6'
gem 'mail'        ,'~> 2.2.7'
gem 'i18n'        ,'~> 0.4.1'
gem 'selenium-client'
