#!/bin/env ruby

# Prints every email address to stdout, uniq'd and sorted.

require 'json'
require 'hashie'

$repos_dir = 'repos'
$git_script_file = 'vim-script.json'

# not bothering to fix these:
# blank, -, /bin/vi@wielders.org, @gmail.com, < initial>< last name>< at>< yahoo>
# b r u c k i e@y a h o o . c o m, heptite () gmail ! com, just ask google
# john undersc0re orr yah00 c0m, leifw@bigfoot , com
# ruben-vim .a.t. ainek.com, s i g z e r o A T g m a i l D O T c o m
# scott@redrubberball.ten (fix the ten to net)
# send2r_at_  gmail _dot_ com, thomas.ibbotson@notthis gmail.com
# vimp reside, xscript in gmx net

emails = {}
repos = Dir.entries($repos_dir).reject { |e| %w{. .. .git}.include?(e) }
repos.sort.each do |dir|
    script = Hashie::Mash.new(JSON.parse(File.read(File.join($repos_dir, dir, $git_script_file))))
    script.versions.each do |v|
        email = v.author.email
        email.gsub!(/\s+[\[(]?at[)\]]?\s+/i, '@')
        email.gsub!(/\s+[\[(]?dot[)\]]?\s+/i, '.')
        emails[v.author.email] = email
    end
end

emails.keys.sort.each { |k| puts emails[k] }
