#!/usr/bin/env ruby

# turns off the issues and wiki tabs for the named repos
# usage: ./turn-off-wiki reponame reponame ...
#    or: ./turn-off-wiki repos/reponame.git repos/reponame.git ...


$:.unshift './lib'
require 'github'

github = Scraper::GitHub.new

ARGV.each do |name|
    # so you can use autocompletion in the repos dir as well
    name =~ /^repos\/(.*)\.git$/
    name = $1 if $1

    github.turn_off_features name
end

