#!/usr/bin/env ruby

# turns off the issues and wiki tabs for the named repos
# usage: ./turn-off-wiki reponame reponame ...
#    or: ./turn-off-wiki repos/reponame.git repos/reponame.git ...


$:.unshift './lib'

require 'bundler'
Bundler.require
require 'github'


github = GitHub.new

ARGV.each do |name|
  # so you can use autocompletion in the repos dir as well
  name =~ /^repos\/(.*)\.git\/?$/
  name = $1 if $1

  puts "  disabling wiki+issues for #{name}"
  github.turn_off_features name
end
